// Agent sessions that outlive browser tabs and server restarts.
//
// Each session runs claude inside its own tmux server (one socket per session,
// so it starts with exactly the env we give it and never touches the user's
// own tmux). The node keeps one tmux client attached through a PTY, buffers
// recent output for replay, and fans output out to any number of viewers.
// On startup, sessions whose tmux server is still alive are re-adopted.

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { execFile } = require('child_process');
const { promisify } = require('util');
const pty = require('node-pty');

const run = promisify(execFile);

const TERMINAL_QUERIES = /\x1b\[[>?=]?[0-9;]*[cn]|\x1b\[>[0-9;]*q|\x1b\][0-9]+;\?(?:\x07|\x1b\\)/g;
const BUFFER_LIMIT = 2 * 1024 * 1024; // chars of recent output kept for replay
const TMUX_CONF = `# Generated by claude-web: tmux is only a persistence layer, so get out of the way.
set -g status off
set -g prefix None
unbind-key -a
set -g escape-time 0
set -g history-limit 50000
set -g window-size latest
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# Draw in the normal screen so lines that scroll off reach the browser's scrollback.
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"
`;

class SessionManager {
  constructor({ stateDir }) {
    this.stateDir = stateDir;
    this.confFile = path.join(stateDir, 'tmux.conf');
    this.indexFile = path.join(stateDir, 'sessions.json');
    this.sessions = new Map(); // id -> session
    fs.mkdirSync(stateDir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(this.confFile, TMUX_CONF);
  }

  tmux(socket, args, opts = {}) {
    return run('tmux', ['-L', socket, '-f', this.confFile, ...args], opts);
  }

  async isAlive(socket) {
    return this.tmux(socket, ['has-session', '-t', 'main']).then(
      () => true,
      () => false
    );
  }

  save() {
    const index = [...this.sessions.values()]
      .filter((s) => s.running)
      .map(({ id, socket, cwd, meta, createdAt }) => ({ id, socket, cwd, meta, createdAt }));
    fs.writeFileSync(this.indexFile, JSON.stringify(index, null, 2), { mode: 0o600 });
  }

  // Pick up sessions left running by a previous server process.
  async restore() {
    let index = [];
    try {
      index = JSON.parse(fs.readFileSync(this.indexFile, 'utf8'));
    } catch {}
    for (const rec of index) {
      if (!(await this.isAlive(rec.socket))) {
        this.cleanupFiles(rec.id);
        continue;
      }
      const s = this.makeSession(rec);
      // Seed the replay buffer with tmux's scrollback so a reopened tab still has history.
      try {
        const { stdout } = await this.tmux(rec.socket, ['capture-pane', '-p', '-e', '-J', '-S', '-5000', '-t', 'main'], {
          maxBuffer: 16 * 1024 * 1024,
        });
        s.buffer = [stdout.replace(/\n/g, '\r\n')];
        s.bufferSize = s.buffer[0].length;
      } catch {}
      this.attachClient(s, 120, 32);
      console.log(`[session ${s.id}] re-adopted (${s.cwd})`);
    }
    this.save();
  }

  makeSession({ id, socket, cwd, meta, createdAt }) {
    const s = {
      id,
      socket,
      cwd,
      meta: meta || {},
      createdAt: createdAt || Date.now(),
      running: true,
      exitCode: null,
      buffer: [],
      bufferSize: 0,
      listeners: new Set(),
      client: null,
      size: { cols: 120, rows: 32 },
    };
    this.sessions.set(id, s);
    return s;
  }

  exitFile(id) {
    return path.join(this.stateDir, `${id}.exit`);
  }

  // tmux leaves its socket file behind when the server exits.
  cleanupFiles(id) {
    fs.rmSync(this.exitFile(id), { force: true });
    const tmpdir = process.env.TMUX_TMPDIR || '/tmp';
    fs.rmSync(path.join(tmpdir, `tmux-${process.getuid()}`, `claude-web-${id}`), { force: true });
  }

  info(s) {
    return { id: s.id, cwd: s.cwd, meta: s.meta, createdAt: s.createdAt, running: s.running, exitCode: s.exitCode };
  }

  list() {
    return [...this.sessions.values()].sort((a, b) => a.createdAt - b.createdAt).map((s) => this.info(s));
  }

  // env is the complete environment for claude; it becomes the tmux server's env.
  async start({ cwd, command, args = [], env, cols = 120, rows = 32, meta }) {
    const id = crypto.randomBytes(6).toString('hex');
    const socket = `claude-web-${id}`;
    // Record claude's exit status, since the tmux session vanishes when it exits.
    const wrapper = 'f=$1; shift; "$@"; echo $? > "$f"';
    await this.tmux(
      socket,
      ['new-session', '-d', '-s', 'main', '-x', String(cols), '-y', String(rows), '-c', cwd, '--',
        '/bin/sh', '-c', wrapper, 'sh', this.exitFile(id), command, ...args],
      { cwd, env }
    );
    const s = this.makeSession({ id, socket, cwd, meta });
    this.attachClient(s, cols, rows);
    this.save();
    console.log(`[session ${id}] ${command} in ${cwd}`);
    return this.info(s);
  }

  // One tmux client per session, owned by the node; viewers come and go.
  attachClient(s, cols, rows) {
    s.size = { cols, rows };
    const client = pty.spawn('tmux', ['-L', s.socket, '-f', this.confFile, 'attach', '-t', 'main'], {
      name: 'xterm-256color',
      cols,
      rows,
      cwd: s.cwd,
      env: { ...process.env, TERM: 'xterm-256color' },
    });
    s.client = client;
    client.onData((data) => {
      s.buffer.push(data);
      s.bufferSize += data.length;
      while (s.bufferSize > BUFFER_LIMIT && s.buffer.length > 1) s.bufferSize -= s.buffer.shift().length;
      for (const fn of s.listeners) fn({ type: 'output', data });
    });
    client.onExit(async () => {
      if (s.client !== client) return; // replaced or killed deliberately
      s.client = null;
      if (await this.isAlive(s.socket)) {
        // Our client died but claude is fine: reattach.
        if (this.sessions.has(s.id)) this.attachClient(s, s.size.cols, s.size.rows);
        return;
      }
      let code = null;
      try {
        code = Number(fs.readFileSync(this.exitFile(s.id), 'utf8').trim());
      } catch {}
      this.cleanupFiles(s.id);
      s.running = false;
      s.exitCode = code;
      this.save();
      console.log(`[session ${s.id}] exited ${code}`);
      for (const fn of s.listeners) fn({ type: 'exit', code });
    });
  }

  // Returns controls for one viewer. onEvent gets {type:'output'|'exit', ...}.
  attach(id, onEvent) {
    const s = this.sessions.get(id);
    if (!s) throw Object.assign(new Error('Session not found.'), { status: 404 });
    // Strip terminal queries (device attributes, version, colors, cursor position) from the
    // replay; otherwise the new viewer's terminal answers them and the replies arrive as keystrokes.
    if (s.buffer.length) onEvent({ type: 'output', data: s.buffer.join('').replace(TERMINAL_QUERIES, '') });
    if (!s.running) onEvent({ type: 'exit', code: s.exitCode });
    s.listeners.add(onEvent);
    return {
      write: (data) => s.client?.write(data),
      resize: (cols, rows) => {
        s.size = { cols, rows };
        s.client?.resize(cols, rows);
      },
      detach: () => s.listeners.delete(onEvent),
    };
  }

  async kill(id) {
    const s = this.sessions.get(id);
    if (!s) return;
    this.sessions.delete(id);
    const client = s.client;
    s.client = null;
    try {
      client?.kill();
    } catch {}
    await this.tmux(s.socket, ['kill-server']).catch(() => {});
    this.cleanupFiles(id);
    for (const fn of s.listeners) fn({ type: 'closed' });
    this.save();
    console.log(`[session ${id}] closed`);
  }
}

module.exports = { SessionManager };
